### ISSUE TITLE
maybe this is a better practice

### ISSUE THREAD

**Issue by i5ting** [rstacruz/simpler-extend#1]
```
var $ = require('./index')

$('Base',{
    constructor: function(name) { 
        this.name = name;
    },
    hello:function(){
        console.log('hello');
    }
})

var base = new Base('a person');

$('Person',base,{
    constructor: function(name) { 
        this.name = name;
    }, 
    say: function(){
        console.log('hello ' + this.name);
        this.hello();
    }
})

var p = new Person('alfred sang');
p.say();
p.hello();
```

https://github.com/i5ting/node-mini-obj

**Comment by rstacruz** [comment]
One issue with this approach is that you need to expose `$` to whatever will subclass your library.

If, for instance, you're writing a `Backbone.Model`-like library where your users are expected to make subclasses of it, it's convenient to just expose one convenient method `.extend()` that's already available from within `Model`.

**Comment by rstacruz** [comment]
Also, node-mini-obj seems to expose global variables like `Class`, and automatically place your classes (like `Person`) in the global context. To each their own, but this isn't something I would personally be comfortable with in a general-purpose library.
